spring.application.name=notificaciones-service
server.port=8082
# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=pedidos360
spring.rabbitmq.password=pedidos360

# Configuracion Pedidos360
pedidos360.rabbitmq.exchange=pedidos.exchange
pedidos360.rabbitmq.queue=pedidos.notificaciones.queue
pedidos360.rabbitmq.routing-key=pedido.creado
pedidos360.rabbitmq.dlx=pedidos.dlx
pedidos360.rabbitmq.dlq=pedidos.dlq
pedidos360.rabbitmq.dlq-routing-key=pedido.fallido
